### ISSUE TITLE
Checklist before open sourcing

### ISSUE THREAD

**Issue by jdppthk** [NVlabs/FourCastNet#1]
- [x] Create universally shared globus directories for model weights, stats and data
- [x]  Add ECMWF data license
- [x] Create staging directory for checkpoints
- [x] Rewrite training readme
- [x] Rewrite inference readme
- [x] Test inference workflow following readme
- [x] remove mins and maxs from stats, training and inference workflow
